# Generated by Django 5.0 on 2025-10-01 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_amount_left'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePetition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(help_text='Name of the movie to be added', max_length=255)),
                ('description', models.TextField(help_text='Why should this movie be added?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Whether this petition has been approved by admin')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitions_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetitionVote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='movies.moviepetition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petition_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('petition', 'user')},
            },
        ),
    ]
